// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"time"
)

type Role struct {
	ID      string
	Name    string
	Status  string
	Created time.Time
	Updated *time.Time
	Deleted *time.Time
}

type User struct {
	ID       string
	Name     string
	Password string
	Email    string
	Status   string
	Created  time.Time
	Updated  *time.Time
	Deleted  *time.Time
}

type Userrole struct {
	ID      string
	Userid  string
	Roleid  string
	Created time.Time
	Updated *time.Time
	Deleted *time.Time
}
