// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: user.sql

package sqlc

import (
	"context"
)

const findUserById = `-- name: FindUserById :one
SELECT id, name, password, email, status, created, updated, deleted FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) FindUserById(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRowContext(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Password,
		&i.Email,
		&i.Status,
		&i.Created,
		&i.Updated,
		&i.Deleted,
	)
	return &i, err
}
