containerPort: 8080

livenessProbe:
  port: 8080
readinessProbe:
  port: 8080
service:
  port: 8080
  type: NodePort
image:
  debug: false
env:
  APP_ENV: local
  LOG_LEVEL: 5
  MYSQL_USER: root
  MYSQL_PASS: password#123
  MYSQL_PORT: 3306
  MYSQL_HOST: mariadb.mariadb.svc.cluster.local
  MYSQL_DB_NAME: mii

