// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: role.sql

package sqlc

import (
	"context"
)

const findRoleById = `-- name: FindRoleById :one
SELECT id, name, status, created, updated, deleted FROM roles
WHERE id = ? LIMIT 1
`

func (q *Queries) FindRoleById(ctx context.Context, id string) (*Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleById, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Created,
		&i.Updated,
		&i.Deleted,
	)
	return &i, err
}
